# https://www.playframework.com/documentation/latest/Configuration
slick.dbs.default.profile = "slick.jdbc.MySQLProfile$"
slick.dbs.default.db.driver = "com.mysql.cj.jdbc.Driver"
slick.dbs.default.db.url = "jdbc:mysql://mysql:3306/valet_db"
slick.dbs.default.db.user = "root"
slick.dbs.default.db.password = "root123"
play.http.secret.key = "change-me-in-docker-change-me-in-docker-change-me-in-docker-123456"