# https://www.playframework.com/documentation/latest/Configuration
slick.dbs.default.profile = "slick.jdbc.MySQLProfile$"
slick.dbs.default.db.driver = "com.mysql.cj.jdbc.Driver"

slick.dbs.default.db {
  driver = "com.mysql.cj.jdbc.Driver"
  url = "jdbc:mysql://localhost:3306/parking_db"
  url = ${?DATABASE_URL}
  user = "root"
  user = ${?DATABASE_USER}
  password = "your_password"
  password = ${?DATABASE_PASSWORD}
}

play.http.secret.key = "change-me-in-docker-change-me-in-docker-change-me-in-docker-123456"

play.filters.csrf.exemptPaths += "/api/.*"

play.cache.redis {
  host = "localhost"
  host = ${?REDIS_HOST}
  port = 6379
  port = ${?REDIS_PORT}
}
play.modules.enabled += "play.api.cache.redis.RedisCacheModule"

pekko.actor.allow-java-serialization = on
pekko.actor.warn-about-java-serializer-usage = off

kafka {
  bootstrap.servers = "localhost:9092"
  bootstrap.servers = ${?KAFKA_BOOTSTRAP_SERVERS}
  topic = "email-notifications"
  smsTopic = "sms-notifications"
}

twilio {
  accountSid = "default_sid"
  accountSid = ${?TWILIO_ACCOUNT_SID}
  authToken = "default_token"
  authToken = ${?TWILIO_AUTH_TOKEN}
  phoneNumber = "default_phone"
  phoneNumber = ${?TWILIO_PHONE_NUMBER}
  defaultCountryCode = "+91"
  defaultCountryCode = ${?TWILIO_DEFAULT_COUNTRY_CODE}
}

play.mailer {
  host = "smtp.gmail.com"
  host = ${?MAIL_HOST}
  port = 587
  port = ${?MAIL_PORT}
  ssl = false
  tls = true
  tls = ${?MAIL_TLS}
  user = "your_email@gmail.com"
  user = ${?MAIL_USER}
  password = "your_app_password"
  password = ${?MAIL_PASSWORD}
  mock = false
}

play.modules.enabled += "modules.KafkaConsumerModule"
