# https://www.playframework.com/documentation/latest/Configuration
slick.dbs.default.profile = "slick.jdbc.MySQLProfile$"
slick.dbs.default.db.driver = "com.mysql.cj.jdbc.Driver"

slick.dbs.default.db {
  driver = "com.mysql.cj.jdbc.Driver"
  url = "jdbc:mysql://localhost:3306/parking_db"
  url = ${?DATABASE_URL}
  user = "root"
  user = ${?DATABASE_USER}
  password = "your_password"
  password = ${?DATABASE_PASSWORD}
}

play.http.secret.key = "change-me-in-docker-change-me-in-docker-change-me-in-docker-123456"

play.filters.csrf.exemptPaths += "/api/.*"
